# Site settings
title: Alexander (Egnod) Lavrov # site title
description: >- # site description
  Backend developer from Saint Petersburg. I work and contribute to open source projects. Write me :)
lang: en-US # default lang
timezone: Europe/Moscow # set your timezone
image: assets/img/ogp.png # This image used for Open Graph more info https://ogp.me/
mode: dark # default theme "dark" | "light"

# Profile settings
author:
  name: Alexander (Egnod) Lavrov # author name
  bio: >- # tell to the world
    Backend developer from Saint Petersburg. I work and contribute to open source projects. Write me :)
    <br />
    <br />
    <a href="assets/resume.pdf" target="_blank" rel="noopener noreferrer"><u><b>Resume</b></u></a>
    <br/>
    GitHub: <a href="https://github.com/egnod" target="_blank" rel="noopener">@egnod</a>
    <br />
    Twitter: <a href="https://twitter.com/egnodus" target="_blank" rel="noopener">@egnodus</a>
    <br/>
    Email: <a href="mailto:external@egnod.dev">external@egnod.dev</a>
  username: egnod # author username
  email: external@egnod.dev # your contact adress
  avatar: /assets/img/avatar.gif # change with your own avatar

# Url settings
url: "http://egnod.dev"
baseurl:
permalink: /:title/
google_analytics:
fb_appid:

# Collection setting
collections:
  posts:
    output: true

# Markdown settings
markdown: kramdown
highlighter: rouge
kramdown:
  syntax_highlighter: rouge

# Default front matter
defaults:
  - scope:
      path: ""
    values:
      layout: post
      comments: false

# Jekyll Compose default front matter
jekyll_compose:
  post_default_front_matter:
    modified:
    tags: []
    description:
  draft_default_front_matter:
    modified:
    tags: []
    description:

# Build settings
sass:
  style: compressed

include:
  - _redirects
  - .htaccess

exclude:
  - CNAME
  - Gemfile
  - Gemfile.lock
  - LICENSE
  - CHANGELOG.md
  - README.md
  - node_modules
  - CODE_OF_CONDUCT.md

# Plugins
plugins:
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-postfiles
